export enum AccountStatus {
    ACCOUNT_CREATED = 'ACCOUNT_CREATED',
    USER_REGISTERED = 'USER_REGISTERED',
    FAILED_TO_CREATE_ACCOUNT = 'FAILED_TO_CREATE_ACCOUNT',
    OTP_SUCCESSFUL = 'OTP_SUCCESSFUL'
}